import type { ComponentDefinition } from "../../shared/types";

export const quoteComponentLibrary: Record<string, ComponentDefinition> = {
  "quote-header": {
    configurableProperties: [
      "companyLogo",
      "companyName",
      "companyAddress",
      "companyEmail",
      "companyPhone",
      "quoteNumber",
      "quoteDate",
      "validityDate",
      "billToName",
      "billToAddress",
      "shipToName",
      "shipToAddress",
    ],
    defaultData: {
      companyLogo:
        "https://iwvduhvsxhjpxapdochp.supabase.co/storage/v1/object/public/app-images/organization-logos/logoipsum-404.svg",
      companyName: "",
      companyAddress: "",
      companyEmail: "",
      companyPhone: "",
      quoteNumber: "",
      quoteDate: "",
      validityDate: "",
      billToName: "",
      billToAddress: "",
      shipToName: "",
      shipToAddress: "",
    },
    defaultStyles: {
      padding: "2rem",
    },
    icon: "FileText",
    label: "Quote Header",
    type: "quote-header",
  },
  "quote-items": {
    configurableProperties: ["items"],
    defaultData: { items: [] },
    defaultStyles: {
      padding: "1rem",
    },
    icon: "List",
    label: "Quote Items",
    type: "quote-items",
  },
  "quote-footer": {
    configurableProperties: [
      "subtotal",
      "taxMode",
      "taxRate",
      "taxAmount",
      "showTaxRate",
      "discountMode",
      "discountRate",
      "discount",
      "showDiscountRate",
      "total",
      "validityPeriod",
      "terms",
    ],
    defaultData: {
      subtotal: "",
      taxMode: "percentage",
      taxRate: "",
      taxAmount: "",
      showTaxRate: true,
      discountMode: "percentage",
      discountRate: "",
      discount: "",
      showDiscountRate: true,
      total: "",
      validityPeriod: "",
      terms: "",
    },
    defaultStyles: {
      padding: "1rem",
    },
    icon: "FileText",
    label: "Quote Footer",
    type: "quote-footer",
  },
};
