import type { ComponentDefinition } from "../types";

export const componentLibrary: Record<string, ComponentDefinition> = {
  certifications: {
    configurableProperties: ["entries"],
    defaultData: { entries: [] },
    defaultStyles: {
      marginTop: "1rem",
      padding: "1rem",
    },
    icon: "Award",
    label: "Certifications",
    type: "certifications",
  },
  education: {
    configurableProperties: ["entries"],
    defaultData: { entries: [] },
    defaultStyles: {
      marginTop: "1rem",
      padding: "1rem",
    },
    icon: "GraduationCap",
    label: "Education",
    type: "education",
  },
  experience: {
    configurableProperties: ["entries"],
    defaultData: { entries: [] },
    defaultStyles: {
      marginTop: "1rem",
      padding: "1rem",
    },
    icon: "Briefcase",
    label: "Work Experience",
    type: "experience",
  },
  header: {
    configurableProperties: [
      "name",
      "title",
      "contact",
      "email",
      "phone",
      "location",
      "socialLinks",
    ],
    defaultData: {
      contact: "",
      email: "",
      location: "",
      name: "",
      phone: "",
      socialLinks: [],
      title: "",
    },
    defaultStyles: {
      backgroundColor: "#ffffff",
      padding: "2rem",
      textAlign: "center",
    },
    icon: "Heading",
    label: "Header",
    type: "header",
  },
  languages: {
    configurableProperties: ["entries"],
    defaultData: { entries: [] },
    defaultStyles: {
      marginTop: "1rem",
      padding: "1rem",
    },
    icon: "Languages",
    label: "Languages",
    type: "languages",
  },
  projects: {
    configurableProperties: ["entries"],
    defaultData: { entries: [] },
    defaultStyles: {
      marginTop: "1rem",
      padding: "1rem",
    },
    icon: "FolderKanban",
    label: "Projects",
    type: "projects",
  },
  skills: {
    configurableProperties: ["items", "category"],
    defaultData: {
      category: "",
      items: [],
    },
    defaultStyles: {
      marginTop: "1rem",
      padding: "1rem",
    },
    icon: "Star",
    label: "Skills",
    type: "skills",
  },
  summary: {
    configurableProperties: ["content"],
    defaultData: {
      content: "",
    },
    defaultStyles: {
      marginTop: "1rem",
      padding: "1rem",
    },
    icon: "FileText",
    label: "Summary",
    type: "summary",
  },
  "invoice-header": {
    configurableProperties: [
      "companyLogo",
      "companyName",
      "companyAddress",
      "companyEmail",
      "companyPhone",
      "invoiceNumber",
      "invoiceDate",
      "dueDate",
      "billToName",
      "billToAddress",
      "shipToName",
      "shipToAddress",
    ],
    defaultData: {
      companyLogo:
        "https://iwvduhvsxhjpxapdochp.supabase.co/storage/v1/object/public/app-images/organization-logos/logoipsum-404.svg",
      companyName: "",
      companyAddress: "",
      companyEmail: "",
      companyPhone: "",
      invoiceNumber: "",
      invoiceDate: "",
      dueDate: "",
      billToName: "",
      billToAddress: "",
      shipToName: "",
      shipToAddress: "",
    },
    defaultStyles: {
      padding: "2rem",
    },
    icon: "FileText",
    label: "Invoice Header",
    type: "invoice-header",
  },
  "invoice-items": {
    configurableProperties: ["items"],
    defaultData: { items: [] },
    defaultStyles: {
      padding: "1rem",
    },
    icon: "List",
    label: "Invoice Items",
    type: "invoice-items",
  },
  "invoice-footer": {
    configurableProperties: [
      "subtotal",
      "taxRate",
      "taxAmount",
      "discount",
      "total",
      "paymentTerms",
      "notes",
    ],
    defaultData: {
      subtotal: "",
      taxRate: "",
      taxAmount: "",
      discount: "",
      total: "",
      paymentTerms: "",
      notes: "",
    },
    defaultStyles: {
      padding: "1rem",
    },
    icon: "FileText",
    label: "Invoice Footer",
    type: "invoice-footer",
  },
};
