import type { ComponentDefinition } from "../../shared/types";

export const estimateComponentLibrary: Record<string, ComponentDefinition> = {
  "estimate-header": {
    configurableProperties: [
      "companyLogo",
      "companyName",
      "companyAddress",
      "companyEmail",
      "companyPhone",
      "estimateNumber",
      "estimateDate",
      "validityDate",
      "billToName",
      "billToAddress",
      "shipToName",
      "shipToAddress",
    ],
    defaultData: {
      companyLogo:
        "https://iwvduhvsxhjpxapdochp.supabase.co/storage/v1/object/public/app-images/organization-logos/logoipsum-404.svg",
      companyName: "",
      companyAddress: "",
      companyEmail: "",
      companyPhone: "",
      estimateNumber: "",
      estimateDate: "",
      validityDate: "",
      billToName: "",
      billToAddress: "",
      shipToName: "",
      shipToAddress: "",
    },
    defaultStyles: {
      padding: "2rem",
    },
    icon: "FileText",
    label: "Estimate Header",
    type: "estimate-header",
  },
  "estimate-items": {
    configurableProperties: ["items"],
    defaultData: { items: [] },
    defaultStyles: {
      padding: "1rem",
    },
    icon: "List",
    label: "Estimate Items",
    type: "estimate-items",
  },
  "estimate-footer": {
    configurableProperties: [
      "subtotal",
      "taxMode",
      "taxRate",
      "taxAmount",
      "showTaxRate",
      "discountMode",
      "discountRate",
      "discount",
      "showDiscountRate",
      "total",
      "validityPeriod",
      "notes",
    ],
    defaultData: {
      subtotal: "",
      taxMode: "percentage",
      taxRate: "",
      taxAmount: "",
      showTaxRate: true,
      discountMode: "percentage",
      discountRate: "",
      discount: "",
      showDiscountRate: true,
      total: "",
      validityPeriod: "",
      notes: "",
    },
    defaultStyles: {
      padding: "1rem",
    },
    icon: "FileText",
    label: "Estimate Footer",
    type: "estimate-footer",
  },
};
