import type { ComponentDefinition } from "../../shared/types";

export const invoiceComponentLibrary: Record<string, ComponentDefinition> = {
  "invoice-header": {
    configurableProperties: [
      "companyLogo",
      "companyName",
      "companyAddress",
      "companyEmail",
      "companyPhone",
      "invoiceNumber",
      "invoiceDate",
      "dueDate",
      "billToName",
      "billToAddress",
      "shipToName",
      "shipToAddress",
    ],
    defaultData: {
      companyLogo:
        "https://iwvduhvsxhjpxapdochp.supabase.co/storage/v1/object/public/app-images/organization-logos/logoipsum-404.svg",
      companyName: "",
      companyAddress: "",
      companyEmail: "",
      companyPhone: "",
      invoiceNumber: "",
      invoiceDate: "",
      dueDate: "",
      billToName: "",
      billToAddress: "",
      shipToName: "",
      shipToAddress: "",
    },
    defaultStyles: {
      padding: "2rem",
    },
    icon: "FileText",
    label: "Invoice Header",
    type: "invoice-header",
  },
  "invoice-items": {
    configurableProperties: ["items"],
    defaultData: { items: [] },
    defaultStyles: {
      padding: "1rem",
    },
    icon: "List",
    label: "Invoice Items",
    type: "invoice-items",
  },
  "invoice-footer": {
    configurableProperties: [
      "subtotal",
      "taxMode",
      "taxRate",
      "taxAmount",
      "showTaxRate",
      "discountMode",
      "discountRate",
      "discount",
      "showDiscountRate",
      "total",
      "paymentTerms",
      "notes",
    ],
    defaultData: {
      subtotal: "",
      taxMode: "percentage",
      taxRate: "",
      taxAmount: "",
      showTaxRate: true,
      discountMode: "percentage",
      discountRate: "",
      discount: "",
      showDiscountRate: true,
      total: "",
      paymentTerms: "",
      notes: "",
    },
    defaultStyles: {
      padding: "1rem",
    },
    icon: "FileText",
    label: "Invoice Footer",
    type: "invoice-footer",
  },
};
